# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - build-essential

sphinx:
  configuration: source/conf.py

python:
  install:
    - requirements: requirements.txt
